name: CI/CD Flask App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible rsync

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/agnel_key
          chmod 600 ~/.ssh/agnel_key
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts
          echo "SSH key configured successfully."

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/agnel_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo Connected successfully to EC2"

      - name: Deploy Flask App via Ansible
        run: |
          ansible-playbook -i "${{ secrets.EC2_HOST }}," \
            --user ${{ secrets.EC2_USER }} \
            --private-key ~/.ssh/agnel_key \
            ansible/deploy_flask.yml
